import { Item } from "../entities/item";

export const ITEMS: Item[] = [
    {
        id: 1,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 2,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 3,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 4,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 5,
        label: 'label',
        brand: 'brand',
        category: 'pc-bureau',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 6,
        label: 'label',
        brand: 'brand',
        category: 'pc-bureau',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 7,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 8,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 9,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 10,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 11,
        label: 'label',
        brand: 'brand',
        category: 'tel-smartphones',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 12,
        label: 'label',
        brand: 'brand',
        category: 'tel-smartphones',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 13,
        label: 'label',
        brand: 'brand',
        category: 'tel-smartphones',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 14,
        label: 'label',
        brand: 'brand',
        category: 'tel-smartphones',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 15,
        label: 'label',
        brand: 'brand',
        category: 'tel-smartphones',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 16,
        label: 'label',
        brand: 'brand',
        category: 'tel-fixes',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 17,
        label: 'label',
        brand: 'brand',
        category: 'tel-fixes',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 18,
        label: 'label',
        brand: 'brand',
        category: 'tel-fixes',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 19,
        label: 'label',
        brand: 'brand',
        category: 'tel-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 20,
        label: 'label',
        brand: 'brand',
        category: 'tel-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 21,
        label: 'label',
        brand: 'brand',
        category: 'stock-dd',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 22,
        label: 'label',
        brand: 'brand',
        category: 'stock-dd',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 23,
        label: 'label',
        brand: 'brand',
        category: 'stock-usb',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 24,
        label: 'label',
        brand: 'brand',
        category: 'stock-usb',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 25,
        label: 'label',
        brand: 'brand',
        category: 'stock-dd',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 26,
        label: 'label',
        brand: 'brand',
        category: 'stock-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
]