import { Item } from "../entities/item";

export const ITEMS: Item[] = [
    {
        id: 1,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 2,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 3,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 4,
        label: 'label',
        brand: 'brand',
        category: 'pc-portable',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 5,
        label: 'label',
        brand: 'brand',
        category: 'pc-bureau',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 6,
        label: 'label',
        brand: 'brand',
        category: 'pc-bureau',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 7,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 8,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 9,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
    {
        id: 10,
        label: 'label',
        brand: 'brand',
        category: 'pc-accessoire',
        price: 100,
        picture: 'https://picsum.photos/300/200',
    },
]